### ISSUE TITLE
SUGESTION

### ISSUE THREAD

**Issue by Cul3r** [Trixtaro/TrixtaLogin#2]
Hellow 
Could you add that when some one logs in he cant attack mobs or when the is in PVP or PVE when some one logs out will die

**Comment by Trixtaro** [comment]
Do you wanna mean that the player must to be invincible before it logs?

**Comment by recruitvfx** [comment]
+1 , could you please add the freeze effect due people starting to login or register?

**Comment by k1r0s** [comment]
in no-premium servers anyone that knows the username of an OP player can just join an run any server command before getting kicked for non loggin in. Would recommend check any bukkit plugin out there that manages auth to see its features preventing players from: moving, chatting (issuing commands), breaking/using stuff before they successfuly log in.

**Comment by Trixtaro** [comment]
It's a good idea but we can't develop that feature that needs to manage permissions because the complexity is high. The 2 colaborators of this plugin already try it to do, but it doesnt works. 
Sponge doesnt provide support for our project because they dont support no-premium servers, what is very sad.

This is a simple solution for now. If anyone can support the project add-in the feature that you request, that will be awesome.

Saludos @k1r0s

**Comment by k1r0s** [comment]
@Trixtaro podemos conversar en privado?

**Comment by Trixtaro** [comment]
Dowload last version 1.3!
